# Generated by Django 5.1.6 on 2025-02-26 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')])),
                ('week_parity', models.CharField(choices=[('all', 'Каждая неделя'), ('even', 'Чётная неделя'), ('odd', 'Нечётная неделя')], default='all', help_text='Укажите, проводится ли занятие на чётных, нечётных или всех неделях', max_length=4)),
                ('duration_minutes', models.PositiveIntegerField(default=90)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queue_site.subject')),
            ],
        ),
    ]
