# Generated by Django 5.1.6 on 2025-02-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_site', '0002_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='week_parity',
            field=models.CharField(choices=[('all', 'Каждая неделя'), ('even', 'Чётная неделя'), ('odd', 'Нечётная неделя')], default='all', max_length=4),
        ),
    ]
