# Generated by Django 5.1.6 on 2025-02-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_site', '0003_alter_schedule_week_parity'),
    ]

    operations = [
        migrations.AddField(
            model_name='labsession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
