# Generated by Django 5.1.6 on 2025-03-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_site', '0005_alter_schedule_day_of_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telegram_id',
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Ваш Telegram username (например, @username). Используется для отправки уведомлений.', max_length=32, null=True, unique=True),
        ),
    ]
