# Generated by Django 5.1.6 on 2025-03-31 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_site', '0007_registrationtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.jpg', help_text='Аватар пользователя.', null=True, upload_to='avatars/'),
        ),
        migrations.CreateModel(
            name='SubjectLabWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queue_site.labwork')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_works', to='queue_site.subject')),
            ],
            options={
                'unique_together': {('subject', 'lab_work')},
            },
        ),
        migrations.CreateModel(
            name='UserLabProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('lab_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queue_site.labwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'lab_work')},
            },
        ),
        migrations.CreateModel(
            name='UserSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='queue_site.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'subject')},
            },
        ),
    ]
